#!/usr/bin/env bash

to_compress=${1-}
archive=${2-}
compression_level=${3:-6}
threads=${4:-0}

[[ -z $1 || $# -gt 4 || $# -lt 2 || ! -e $to_compress || -f "$archive".tar.xz ]] && {
    printf '%s\n' "${0##*'/'} <to_compress> <new_file> <compression level 0-9(6)> <threads(0)>"
    exit 1
}

# Invalid integer provided for compression level
(( compression_level < 0 || compression_level > 9 )) && {
    printf '%s\n' "Invalid compression level requested (valid range 0-9): \"$compression_level\""
    exit 2
}

# If .tar.xz was provided remove it
# to support adding it if it wasn't
archive=${archive//.tar.xz}

tar -c "$to_compress" | xz -T"$threads" -"$compression_level" - > "$archive".tar.xz
