#!/usr/bin/env bash

# Configuration
sDOWNLOADS_PATH="$HOME"/Downloads/test
sMOVIES_PATH="$sDOWNLOADS_PATH"/movies
sFILE_MATCH_LIST="names.txt"
sFIND_EXT="mp4"
iCOUNTER_UNIQUE_FILE=0
iCOUNTER_DUPLICATE_FILE=0

[[ ! -d $sDOWNLOADS_PATH || ! -d $sMOVIES_PATH || ! -f $sFILE_MATCH_LIST || ! -r $sFILE_MATCH_LIST ]] && { echo "(L$LINENO) Configuration error"; exit 1; }

while IFS= read -r sFIND_FILE_FULL_NAME; do
    sFIND_FILE_BASENAME=${sFIND_FILE_FULL_NAME##*/}
    sFIND_FILE_EXT=${sFIND_FILE_BASENAME##*.}
    while IFS= read -r sBASE_PATTERN; do
        sBASE_PATTERN_LEFT=${sBASE_PATTERN%[[:space:]]*}
        sBASE_PATTERN_RIGHT=${sBASE_PATTERN#*[[:space:]]}
        if [[ $sFIND_FILE_BASENAME =~ ^${sBASE_PATTERN_LEFT}[._]${sBASE_PATTERN_RIGHT}\.${sFIND_EXT}$ ]]; then
            for sDEST_PATH in "$sMOVIES_PATH/"*; do
                sDEST_PATH_BASENAME=${sDEST_PATH##*/}
                if [[ -d $sDEST_PATH ]]; then
                    if [[ $sDEST_PATH_BASENAME = "$sBASE_PATTERN" ]]; then
                        if [[ -f $sDEST_PATH/$sFIND_FILE_BASENAME ]]; then
                            iCOUNTER_DUPLICATE_FILE=$((iCOUNTER_DUPLICATE_FILE+1))
                            echo "mv \"$sFIND_FILE_FULL_NAME\" \"$sDEST_PATH/${sFIND_FILE_BASENAME/%.$sFIND_FILE_EXT/_$RANDOM.$sFIND_FILE_EXT}\""
                            #mv "$sFIND_FILE_FULL_NAME" "$sDEST_PATH/${sFIND_FILE_BASENAME/%.$sFIND_FILE_EXT/_$RANDOM.$sFIND_FILE_EXT}"
                            break 1
                        else
                            iCOUNTER_UNIQUE_FILE=$((iCOUNTER_UNIQUE_FILE+1))
                            echo "mv \"$sFIND_FILE_FULL_NAME\" \"$sDEST_PATH/$sFIND_FILE_BASENAME\""
                            #mv "$sFIND_FILE_FULL_NAME" "$sDEST_PATH/$sFIND_FILE_BASENAME"
                            break 1
                        fi
                    fi
                fi
            done
        fi
    done <"$sFILE_MATCH_LIST"
done < <(find "$sDOWNLOADS_PATH" -type f ! -name "*${0##*/}" ! -name "*${sFILE_MATCH_LIST}" ! -path "${sMOVIES_PATH}/*" -name "*.${sFIND_EXT}")

echo "Moved $iCOUNTER_UNIQUE_FILE unique files and $iCOUNTER_DUPLICATE_FILE files that were renamed"
