#!/usr/bin/env bash

sSHADERS_PATH="/usr/share/reshade/shaders"

for fxfile in "$sSHADERS_PATH"/*.fx; do
    [[ -f $fxfile ]] && {
        printf "%s = %s\n" "$(basename "${fxfile,,}" .fx)" "\"$fxfile\""
    }
done

