#!/usr/bin/env bash

# $1 parameter = user@host
# $2 parameter = remote path to search
# $3 parameter = checksum application (md5sum, sha256sum, sha512sum, etc.)

declare -a files=() checksums=()
declare ssh_string='ssh' \
        connect_to=${1:-'user@host'} \
        ciphers='chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com' \
        checksum=${3:-'sha512sum'} \
        base_path=${2:-'/tmp'} \
        time_start=0 \
        time_end=0 \
        i=0

FindFilesandChecksums()
{

    files=()
    checksums=()

    # Parse the output of find via ssh, adding each column element to its respective array
    time_start=$(date '+%s')
    while IFS= read -r || [[ -n $REPLY ]]
    do
        [[ $REPLY =~ ^$'\n'$ ]] && continue
        files+=("${REPLY##*[[:blank:]]}")
        checksums+=("${REPLY%%[[:blank:]]*}")
    done < <("$ssh_string" -c "$ciphers" "$connect_to" find "$base_path" -type f  ! -path '*dev/*' ! -path '*proc/*' -exec "$checksum" '{}' + \; 2>/dev/null | LC_ALL=C sort -fk2.3) #  | sed "s|$base_path||g"
    time_end=$(date '+%s')

    # Report
    printf '%s\n' "Found and sorted ${#files[@]} files and calculated ${#checksums[@]} checksums in $(( time_end - time_start )) seconds"

}

FindSortFiles()
{

    files=()

    # Parse the output of find via ssh, adding each column element to its respective array
    time_start=$(date '+%s')
    while IFS= read -r || [[ -n $REPLY ]]
    do
        [[ $REPLY =~ ^$'\n'$ ]] && continue
        files+=("$REPLY")
    done < <("$ssh_string" -c "$ciphers" "$connect_to" find "$base_path" -type f ! -path '*dev/*' ! -path '*proc/*' 2>/dev/null | LC_ALL=C sort -f) # ! -path '*.git*'
    time_end=$(date '+%s')

    # Report
    printf '%s\n' "Found and sorted ${#files[@]} files in $(( time_end - time_start )) seconds"

}

FindFiles()
{

    files=()

    # Parse the output of find via ssh, adding each column element to its respective array
    time_start=$(date '+%s')
    while IFS= read -r || [[ -n $REPLY ]]
    do
        [[ $REPLY =~ ^$'\n'$ ]] && continue
        files+=("$REPLY")
    done < <("$ssh_string" -c "$ciphers" "$connect_to" find "$base_path" -type f ! -path '*dev/*' ! -path '*proc/*' 2>/dev/null) # ! -path '*.git*'
    time_end=$(date '+%s')

    # Report
    printf '%s\n' "Found ${#files[@]} files in $(( time_end - time_start )) seconds"

}

PrintChecksumsFiles()
{

    # List each element of each array in a similar format to {md,sha}*sum
    for i in "${!files[@]}"
    do
        printf '%s  %s\n' "${checksums[i]}" "${files[i]}" # "${files[i]/#$base_path}"
    done

}

PrintFiles()
{

    # List each element of each array in a similar format to {md,sha}*sum
    for i in "${!files[@]}"
    do
        printf '%s\n' "${files[i]}" # "${files[i]/#$base_path}"
    done

}

QueryHostCiphers()
{

    opts=(cipher cipher-auth mac kex key key-cert key-plain key-sig sig)
    for option in "${opts[@]}"
    do
        printf '\n%s\n' "$option:"
        "$ssh_string" -Q "$option" "$connect_to"
    done

}

##QueryHostCiphers
##FindFilesandChecksums
##ListAllFiles

##FindSortFiles
FindFiles
##PrintFiles
