#! /usr/bin/env bash

# Replace the following with info pertinent to your set-up
DOMAIN="example.org"
URL="https://$DOMAIN/uploads/";
SAVE_PATH="/home/frank/http/uploads/"
SSH_STRING="ssh -p 666"
SSH_USER="frank"
# All done

TOTAL_SLASHES=$(echo "$SAVE_PATH" | tr -cd '/' | wc -c)
CUT_AFTER=$((TOTAL_SLASHES+1))

function get_file_list {
  CLOUD_FILES=($($SSH_STRING "$SSH_USER"@"$DOMAIN" find "$SAVE_PATH" -type f | cut -d '/' -f "$CUT_AFTER"-))
  COUNT=0
  if [ ${#CLOUD_FILES[@]} -gt 0 ]; then
    ((COUNT++))
    for i in ${CLOUD_FILES[@]}
    do
      echo -e "$COUNT $URL$i\n"
      ((COUNT++))
    done | column -t
  else
    echo "Nothing to list"
  fi
}

if [ $# -eq 0 ]; then
    echo -e "\nNo arguments provided\n\nUsage:\n\ttovps path/to/file - upload file\n\ttovps list - list files currently on the server\n\ttovps del - delete a file on the server"
    exit 1
  else
    case $1 in
      list)
        get_file_list
        ;;

      del)
        get_file_list
        if [ $COUNT -gt 0 ]; then
          if [ ${#CLOUD_FILES[@]} -gt 1 ]; then
            read -p "Delete which file [1-${#CLOUD_FILES[@]}]: " DELNUM
          else
            read -p "Delete this file? [y/n] " DELCHAR
            if [ "$DELCHAR" == "y" ]; then
              DELNUM=1
            fi
          fi

          [ -n "$DELNUM" ] && [ "$DELNUM" -eq "$DELNUM" ] 2>/dev/null
            if [ $? -ne 0 ]; then
               echo "Nothing deleted."
               exit 1
            fi

          if [ "$DELNUM" -lt 1 ] || [ "$DELNUM" -gt ${#CLOUD_FILES[@]} ]; then
            echo "Nothing deleted."
            exit 1
          fi

          DELCOUNT=1
          for i in ${CLOUD_FILES[@]}
          do
            if [ $DELNUM -eq $DELCOUNT ]; then
              DELFILE=$i
              DELDIR="${DELFILE%/*}"
            fi
            ((DELCOUNT++))
          done
          echo "Deleting: $DELFILE"
          $($SSH_STRING "$DOMAIN" rm -r "$SAVE_PATH$DELDIR")
          echo "Done!"

        fi
        ;;
      *)
        if [ ! -f "$1" ]; then
          echo -e "$1 does not exist."
        else
          FILENAME=$(basename "$1")
          DIR=$(md5sum "$1" | cut -d ' ' -f1)
          RSYNC_PATH="mkdir -p $SAVE_PATH$DIR && rsync"
          RSYNC_OPTIONS=(-rzv -e "$SSH_STRING" --rsync-path="$RSYNC_PATH")
          rsync "${RSYNC_OPTIONS[@]}" "$1" "$SSH_USER"@"$DOMAIN":"$SAVE_PATH$DIR/"
          MD5_SUM=$($SSH_STRING "$SSH_USER"@"$DOMAIN" md5sum $SAVE_PATH$DIR/$FILENAME | cut -d ' ' -f1)

          echo "Local file's md5sum: $MD5_SUM"
          echo "Remote file's md5sum: $MD5_SUM"
          if [ $MD5_SUM == $DIR ]; then
            echo "Transfer successful!"
            echo -e "\nYou can access the file here: $URL$DIR/$FILENAME"
            echo "(copied to clipboard)"
            echo "$URL$DIR/$FILENAME" | xclip -r
          else
            echo "md5sums do not match! Please try again."
          fi
        fi
    esac
fi

